### PR TITLE
Text Customisation in ConversationView

### PR DESCRIPTION
**Pull request by howawong**
- Message Status

1. Delivering
2. Delivered
3. Some Read
4. All Read

- Text Message Place holder

- Date Format

Connects #101

### CODE REVIEW

**Comment by howawong** [comment]
Sample Usage
```xml
<?xml version="1.0" encoding="utf-8"?>
<io.skygear.plugins.chat.ui.ConversationView
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    uikit:someRead="Read + 1"
    uikit:delivered="Received"
    uikit:delivering="Sending"
    uikit:allRead="Read + X"
    uikit:hint="Typer somthing"
    uikit:dateFormat="HH:MM:ss"
    xmlns:uikit="http://schemas.android.com/apk/res-auto"
    xmlns:android="http://schemas.android.com/apk/res/android" />
```

**Comment by carmenlau** [comment]
If user want to support localized string, can user set the attribute by runtime like `getString(R.string.hello)`? Is it possible? thanks!

**Comment by howawong** [comment]
Of course, actually I recommend ```uikit:delivered="@string/delivered_text"```.

**Comment by howawong** [comment]
Continue at #126

**Pull request closed without merging**
