### PR TITLE
WIP: Add conversation view to UIKit

### PR DESCRIPTION
**Pull request by ben181231**
connect #42

### CODE REVIEW

**Comment by carmenlau** [comment]
Got following exception when entering conversation view

```
09-27 19:25:47.449 29712-29712/io.skygear.chatexample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: io.skygear.chatexample, PID: 29712
                                                                        java.util.NoSuchElementException: List is empty.
                                                                            at kotlin.collections.CollectionsKt___CollectionsKt.last(_Collections.kt:341)
                                                                            at io.skygear.plugins.chat.ui.ConversationFragment.addMessages(ConversationFragment.kt:171)
                                                                            at io.skygear.plugins.chat.ui.ConversationFragment.addMessages$default(ConversationFragment.kt:145)
                                                                            at io.skygear.plugins.chat.ui.ConversationFragment$onResume$$inlined$let$lambda$2.onSucc(ConversationFragment.kt:122)
                                                                            at io.skygear.plugins.chat.ui.ConversationFragment$onResume$$inlined$let$lambda$2.onSucc(ConversationFragment.kt:119)
                                                                            at io.skygear.plugins.chat.ChatContainer$9.onLambdaSuccess(ChatContainer.java:641)
                                                                            at io.skygear.skygear.LambdaResponseHandler.onSuccess(LambdaResponseHandler.java:42)
                                                                            at io.skygear.skygear.Request.onResponse(Request.java:110)
                                                                            at io.skygear.skygear.Request.onResponse(Request.java:31)
                                                                            at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
                                                                            at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
                                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
09-27 19:25:47.605 29712-29729/io.skygear.chatexample E/Volley: [1208] BasicNetwork.performRequest: Unexpected response code 400 for https://carmenlau.staging.skygeario.com/chat/mark_as_delivered
```

**Comment by ben181231** [comment]
@carmenlau still get that exception? I cannot reproduce that.

**Comment by carmenlau** [comment]
It only happen when I enter a newly created conversation.

Maybe we check the `msgs.size` before calling
```
val lastChatMsg = msgs.last().chatMessage
this.skygearChat?.markConversationLastReadMessage(conv, lastChatMsg)
```
?

**Comment by ben181231** [comment]
Oh... I see.

**Pull request merged**
