### PR TITLE
WIP: Enable sending and receiving voice messages

### PR DESCRIPTION
**Pull request by ben181231**
connect #50

### CODE REVIEW

**Comment by ben181231** [comment]
@carmenlau This PR is still WIP. What is done up till now is the UI part (i.e. the voice message button). The following items are pending:

- [ ] Record voice message
- [ ] Send voice message with correct meta data
- [ ] Display voice message
- [ ] Play voice message

**Comment by carmenlau** [comment]
Have you encountered any problems when working on this that needs help or discussion?
Can you please also help adding estimation to the remaining items? For the chat kit planning 
Great thanks! @ben181231 🙇🏻‍♀️

**Comment by ben181231** [comment]
@carmenlau I have updated the items with a rough estimation marked.

**Comment by carmenlau** [comment]
Thanks @ben181231

**Comment by carmenlau** [comment]
@ben181231 The PR is great and recording ui effect is really nice!! But is it easy for us change the style of input bar height, the edittext and add button? The original `MessageInput` looks more beautiful, although we cannot use it now maybe we can update input bar to similar style?

device-2017-10-11-233158

**Comment by ben181231** [comment]
@carmenlau 

The PR now should be completed except some UX issues:

- Loading state for voice message
- Caching for voice message
- Displaying playing time

**Comment by carmenlau** [comment]
@ben181231 Just tried but I cannot record the voice. And when the first time I clicked the record button the permission dialog is shown but the app crash :(

Testing video:
https://www.dropbox.com/s/zai567qfwowgbyl/IMG_1791.MOV?dl=0

**Comment by carmenlau** [comment]
Merged to master via 74cd376

**Pull request closed without merging**
