### PR TITLE
Separate UI Kit Classes from chat project

### PR DESCRIPTION
**Pull request by howawong**
1. Create chat_ui project
2. Move io.skygear.plugins.chat.ui classes into chat_ui project
3. Add bintray script
4. Update script/deploy.sh
5. Add :chat_ui:build into .travis.yml

Connects #81

### CODE REVIEW

**Comment by howawong** [comment]
@carmenlau  I sent a message to request bintray to include the package in jcenter, will update the PR after it is approved.

**Comment by howawong** [comment]
skygear-chat-android-uikit is now at jcenter. https://bintray.com/bintray/jcenter?filterByPkgName=skygear-chat-android

screen shot 2017-12-08 at 3 01 34 am

@carmenlau  please check and merge the PR, thx.

**Comment by carmenlau** [comment]
Thanks @howawong Can you also help updating the guides? Just similar to the ios version is fine.
https://docs.skygear.io/guides/chat/quick-start/android/

And how can I import the uikit from github? I imported it the chat sdk this way
```
compile 'com.github.skygeario:chat-sdk-android:master-SNAPSHOT'
```

thank you~!

**Comment by howawong** [comment]
`compile 'io.skygear.plugins:chat_ui:1.1.3'`

or 

`compile 'io.skygear.plugins:chat_ui:+'`

**Comment by howawong** [comment]
I think jitpack remains unchanged. because in `settings.gradle` chat and chat_ui are included.

**Comment by carmenlau** [comment]
@howawong I tried using your commit in the demo app. Got dependeny error as follow, do i miss something?

```
Error:Conflict with dependency 'com.google.code.findbugs:jsr305' in project ':app'. Resolved versions for app (3.0.2) and test app (2.0.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Error:Module 'com.github.howawong-oursky:chat-sdk-android:4e2cef4' depends on one or more Android Libraries but is a jar
```

I changed the app chat dependencies like this
```
compile 'com.github.howawong-oursky:chat-sdk-android:4e2cef4'
```

**Comment by howawong** [comment]
I downgraded the minSDKVersion from 19 to 16 in chat_ui. Can you try again with `576754e` ?

**Comment by carmenlau** [comment]
Just tried and still got the error :(

```
Error:Module 'com.github.howawong-oursky:chat-sdk-android:576754e' depends on one or more Android Libraries but is a jar
```

**Comment by howawong** [comment]
I think it is mixed with jcenter repo, can you try
`compile 'com.github.howawong-oursky:chat-sdk-android: 576754e@aar'`

**Comment by carmenlau** [comment]
Seems jitpack doesn't support `@arr` >"<

```
Error:Could not find chat-sdk-android.aar (com.github.howawong-oursky:chat-sdk-android:576754e).
Searched in the following locations:
    https://jitpack.io/com/github/howawong-oursky/chat-sdk-android/576754e/chat-sdk-android-576754e.aar
```

**Comment by howawong** [comment]
I just checked out a clean copy and with the following diff, and then I can build the demo. What version of gradle plugin and Android studio are you using?

```diff
diff --git a/app/build.gradle b/app/build.gradle
index b575e0f..dc446ce 100644
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -25,7 +25,7 @@ dependencies {
         exclude group: 'com.android.support', module: 'support-annotations'
     })
     compile 'io.skygear:skygear:+'
-    compile 'io.skygear.plugins:chat:1.1.3'
+    compile 'com.github.howawong-oursky:chat-sdk-android:576754e'
     compile 'com.android.support:appcompat-v7:26.+'
     compile 'com.android.support.constraint:constraint-layout:1.0.2'
     compile 'com.android.support:design:26.+'
diff --git a/build.gradle b/build.gradle
index feae75e..7408a21 100644
--- a/build.gradle
+++ b/build.gradle
@@ -5,7 +5,7 @@ buildscript {
         jcenter()
     }
     dependencies {
-        classpath 'com.android.tools.build:gradle:2.3.3'
+        classpath 'com.android.tools.build:gradle:3.0.1'
 
         // NOTE: Do not place your application dependencies here; they belong
         // in the individual module build.gradle files
diff --git a/gradle/wrapper/gradle-wrapper.properties b/gradle/wrapper/gradle-wrapper.properties
index ef42fc6..9c36894 100644
--- a/gradle/wrapper/gradle-wrapper.properties
+++ b/gradle/wrapper/gradle-wrapper.properties
@@ -1,6 +1,6 @@
-#Mon Oct 16 15:21:30 HKT 2017
+#Fri Dec 15 17:31:26 HKT 2017
 distributionBase=GRADLE_USER_HOME
 distributionPath=wrapper/dists
 zipStoreBase=GRADLE_USER_HOME
 zipStorePath=wrapper/dists
-distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
```

**Comment by carmenlau** [comment]
My android studio is 3.0.1 and this is my project setting

screen shot 2017-12-15 at 5 52 18 pm

Maybe let me also try check a clean copy

**Comment by howawong** [comment]
screen shot 2017-12-15 at 6 04 04 pm
Mine is different from yours...

**Comment by carmenlau** [comment]
@howawong 
I tired in gradle3.3, master branch ok, but seperate uikit branch has error
In gradle 4.4, both branches work great. After more check, it looks like jitpack problem to me that the aar link is not valid. As long as it works on jcenter i think it is ok. Do jcenter has alpha channel or support snapshot? So we can test

**Comment by howawong** [comment]
@carmenlau jcenter does not have any specific feature like this but I think uploading a binary naming it as 1.x.x-alpha is fine.

**Comment by carmenlau** [comment]
@howawong If we upload `1.x.x-alpha` to jcenter, when user use `compile 'io.skygear.plugins:chat:+'` They will only get the stable release but not the alpha one? If so, maybe we could try submit alpha and do the test. :)

**Comment by howawong** [comment]
Continue at #123

**Pull request closed without merging**
